import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from '@clerk/nextjs'
import { Navbar } from "@/app/components/Navbar";
import { Footer } from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Spend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en">
            <body
                className={cn(
                    'antialiased',
                    inter.className
                )}
            >
                <Navbar/>
                  {children}
                <Footer/>
            </body>
        </html>
    </ClerkProvider>
  );
}
