import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Footer } from "@/app/components/Footer";
import { cn } from "@/lib/utils";
import { Navbar } from "../components/Navbar";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Spend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
            'antialiased',
            inter.className
          )}
      >
        <Navbar />
        <main className="min-h-[calc(100vh-3rem)]">
            {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
