import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "sonner";
import React from "react";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Spend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', inter.className)}>
        <ClerkProvider>
          <Providers>
            <Toaster richColors position="bottom-right" />
            {children}
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
